import { Client } from "pg";
import { argon2idAsync } from "@noble/hashes/argon2.js";

const encoder = new TextEncoder();
const allowedAvatarTypes = new Set(["image/jpeg", "image/png", "image/webp", "image/gif", "image/heic", "image/heif"]);
const argon2Defaults = { m: 65536, t: 3, p: 4, version: 0x13, dkLen: 32, asyncTick: 10 };

class ApiError extends Error { constructor(message, status = 400) { super(message); this.status = status; } }
class ConfigurationError extends Error {}

function cors(request) { return { "access-control-allow-origin": request.headers.get("origin") || "*", "access-control-allow-methods": "GET, POST, PATCH, DELETE, OPTIONS", "access-control-allow-headers": "Authorization, Content-Type", vary: "Origin" }; }
function json(data, status, request) { return Response.json(data, { status, headers: cors(request) }); }
function now() { return new Date(); }
function today() { return new Date().toISOString().slice(0, 10); }
function uuid() { return crypto.randomUUID(); }
function addMinutes(minutes) { return new Date(Date.now() + minutes * 60_000); }
function addDays(days) { return new Date(Date.now() + days * 86_400_000); }
function requireString(value, name, min = 1, max = 65_535) { if (typeof value !== "string" || value.trim().length < min || value.trim().length > max) throw new ApiError(`${name} is invalid.`, 422); return value.trim(); }
async function body(request) { try { return await request.json(); } catch { throw new ApiError("Request body must be valid JSON.", 400); } }

function b64(bytes) { let output = ""; for (const byte of bytes) output += String.fromCharCode(byte); return btoa(output).replace(/=+$/, ""); }
function fromB64(value) { const padded = value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - value.length % 4) % 4); return Uint8Array.from(atob(padded), (char) => char.charCodeAt(0)); }
function b64url(bytes) { return b64(bytes).replace(/\+/g, "-").replace(/\//g, "_"); }
function timingSafeEqual(left, right) { if (left.length !== right.length) return false; let difference = 0; for (let index = 0; index < left.length; index += 1) difference |= left[index] ^ right[index]; return difference === 0; }

// Pwdlib's recommended Argon2id PHC format is retained, so existing users and
// refresh-token sessions stored by the Python service remain valid.
function parseArgon2(encoded) {
  const parts = String(encoded || "").split("$");
  if (parts.length !== 6 || parts[1] !== "argon2id") return null;
  const values = Object.fromEntries(parts[3].split(",").map((pair) => pair.split("=")));
  const m = Number(values.m); const t = Number(values.t); const p = Number(values.p);
  const version = Number(parts[2].replace("v=", ""));
  if (![m, t, p, version].every(Number.isFinite)) return null;
  return { salt: fromB64(parts[4]), hash: fromB64(parts[5]), m, t, p, version };
}
async function hashSecret(value) { const salt = crypto.getRandomValues(new Uint8Array(16)); const hash = await argon2idAsync(encoder.encode(value), salt, argon2Defaults); return `$argon2id$v=19$m=65536,t=3,p=4$${b64(salt)}$${b64(hash)}`; }
async function verifySecret(value, encoded) { const details = parseArgon2(encoded); if (!details) return false; const hash = await argon2idAsync(encoder.encode(value), details.salt, { m: details.m, t: details.t, p: details.p, version: details.version, dkLen: details.hash.length, asyncTick: 10 }); return timingSafeEqual(hash, details.hash); }

async function signJwt(payload, secret) { const header = b64url(encoder.encode(JSON.stringify({ alg: "HS256", typ: "JWT" }))); const content = b64url(encoder.encode(JSON.stringify(payload))); const key = await crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const signature = await crypto.subtle.sign("HMAC", key, encoder.encode(`${header}.${content}`)); return `${header}.${content}.${b64url(new Uint8Array(signature))}`; }
async function readJwt(token, secret) { const [header, content, signature] = String(token || "").split("."); if (!header || !content || !signature) throw new Error("Invalid token"); const key = await crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["verify"]); if (!(await crypto.subtle.verify("HMAC", key, fromB64(signature), encoder.encode(`${header}.${content}`)))) throw new Error("Invalid token"); const payload = JSON.parse(new TextDecoder().decode(fromB64(content))); if (!payload.exp || payload.exp <= Math.floor(Date.now() / 1000)) throw new Error("Expired token"); return payload; }
async function tokenPair(userId, env) { if (!env.JWT_SECRET_KEY) throw new ConfigurationError("JWT_SECRET_KEY is missing."); const stamp = Math.floor(Date.now() / 1000); const accessMinutes = Number(env.ACCESS_TOKEN_EXPIRE_MINUTES || 60); const refreshDays = Number(env.REFRESH_TOKEN_EXPIRE_DAYS || 30); return { access_token: await signJwt({ sub: userId, exp: stamp + accessMinutes * 60, type: "access" }, env.JWT_SECRET_KEY), refresh_token: await signJwt({ sub: userId, exp: stamp + refreshDays * 86400, type: "refresh" }, env.JWT_SECRET_KEY), token_type: "bearer" }; }

async function withDb(env, callback) { if (!env.HYPERDRIVE?.connectionString) throw new ConfigurationError("HYPERDRIVE binding is missing."); const client = new Client({ connectionString: env.HYPERDRIVE.connectionString }); await client.connect(); try { return await callback(client); } finally { await client.end(); } }
async function currentUser(request, env, db, optional = false) { const authorization = request.headers.get("authorization") || ""; if (!authorization.startsWith("Bearer ")) { if (optional) return null; throw new ApiError("Not authenticated.", 401); } try { const payload = await readJwt(authorization.slice(7), env.JWT_SECRET_KEY); if (payload.type !== "access" || !payload.sub) throw new Error("Wrong token"); const { rows } = await db.query("SELECT * FROM users WHERE id = $1", [payload.sub]); if (!rows[0] || !rows[0].is_active) throw new Error("Inactive"); return rows[0]; } catch { if (optional) return null; throw new ApiError("Invalid or expired authentication token.", 401); } }
function userResponse(user) { return { id: user.id, username: user.username, email: user.email, is_verified: Boolean(user.is_verified), is_active: Boolean(user.is_active), refer_id: user.refer_id, avatar_url: user.avatar_url, created_at: user.created_at }; }
function couponTier(streak, referrals) { if (streak >= 30 && referrals >= 5) return "Star"; if (streak >= 20 && referrals >= 10) return "Diamond"; if (streak >= 12 && referrals >= 5) return "Gold"; if (streak >= 5 && referrals >= 3) return "Silver"; return null; }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]); }
function otpEmail(username, otp) { return `<div style="font-family:Arial,sans-serif"><h2>Verify your WebX account</h2><p>Hi ${escapeHtml(username)},</p><p>Your verification code is:</p><p style="font-size:28px;letter-spacing:6px;font-weight:bold">${otp}</p><p>This code expires in 5 minutes.</p></div>`; }
function otpCode() { return Array.from(crypto.getRandomValues(new Uint32Array(6)), (value) => value % 10).join(""); }
async function sendOtp(env, user, otp) { if (!env.BREVO_API_KEY || !env.BREVO_FROM_EMAIL) throw new ConfigurationError("Brevo email secrets are missing."); const response = await fetch("https://api.brevo.com/v3/smtp/email", { method: "POST", headers: { "api-key": env.BREVO_API_KEY, "content-type": "application/json", accept: "application/json" }, body: JSON.stringify({ sender: { email: env.BREVO_FROM_EMAIL, name: env.APP_NAME || "WebX" }, to: [{ email: user.email, name: user.username }], subject: "Verify your WebX account", htmlContent: otpEmail(user.username, otp) }) }); if (!response.ok) throw new ApiError("Unable to send verification email.", 502); }
async function issueOtp(env, db, user) { const otp = otpCode(); await db.query("DELETE FROM otps WHERE user_id = $1", [user.id]); await db.query("INSERT INTO otps (id, user_id, otp_hash, purpose, created_at, expires_at, attempts, is_used) VALUES ($1,$2,$3,'EMAIL_VERIFICATION',$4,$5,0,false)", [uuid(), user.id, await hashSecret(otp), now(), addMinutes(5)]); await sendOtp(env, user, otp); }
async function streakResponse(db, user) { let { rows: [streak] } = await db.query("SELECT * FROM streaks WHERE user_id = $1", [user.id]); if (!streak) { const id = uuid(); ({ rows: [streak] } = await db.query("INSERT INTO streaks (id,user_id,current_streak,highest_streak,last_claim_date) VALUES ($1,$2,0,0,NULL) RETURNING *", [id, user.id])); } const { rows: [referrals] } = await db.query("SELECT COUNT(*)::int AS count FROM referrals WHERE referrer_id = $1", [user.id]); const daysOld = streak.last_claim_date ? Math.floor((Date.now() - Date.parse(`${streak.last_claim_date}T00:00:00Z`)) / 86_400_000) : Infinity; return { ...streak, kyc_eligible: streak.current_streak >= 3 && daysOld <= 1, star_coupon_tier: couponTier(streak.current_streak, referrals.count) }; }

async function handleApi(request, env, db) {
  const path = new URL(request.url).pathname.replace(/\/$/, "") || "/"; const method = request.method;
  if (path === "/" && method === "GET") return json({ message: `${env.APP_NAME || "WebX API"} Backend`, version: "1.0.0", docs_url: null }, 200, request);
  if (path === "/api/v1/auth/register" && method === "POST") { const data = await body(request); const username = requireString(data.username, "username", 3, 30); const email = requireString(data.email, "email", 3, 255).toLowerCase(); const password = requireString(data.password, "password", 6); if (!/^[A-Za-z0-9_]+$/.test(username) || !/^\S+@\S+\.\S+$/.test(email)) throw new ApiError("Registration data is invalid.", 422); const { rows: [existing] } = await db.query("SELECT email, username FROM users WHERE email = $1 OR username = $2", [email, username]); if (existing) throw new ApiError(existing.email === email ? "Email is already registered." : "Username is already taken.", 400); const user = { id: uuid(), username, email, hashed_password: await hashSecret(password), is_verified: false, is_active: true, refer_id: null, avatar_url: null, created_at: now() }; await db.query("INSERT INTO users (id,username,email,hashed_password,is_verified,is_active,created_at,updated_at) VALUES ($1,$2,$3,$4,false,true,$5,$5)", [user.id,user.username,user.email,user.hashed_password,user.created_at]); await issueOtp(env, db, user); return json(userResponse(user), 201, request); }
  if (path === "/api/v1/auth/verify-otp" && method === "POST") { const data = await body(request); const email = requireString(data.email,"email").toLowerCase(); const otpValue = requireString(data.otp,"otp",6,6); const { rows:[user] } = await db.query("SELECT * FROM users WHERE email = $1",[email]); if (!user) throw new ApiError("User not found.",404); if (!user.is_verified) { const { rows:[otp] } = await db.query("SELECT * FROM otps WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1",[user.id]); if (!otp) throw new ApiError("No active OTP found. Please request a new one.",400); if (otp.is_used) throw new ApiError("OTP has already been used.",400); if (new Date(otp.expires_at) < now()) { await db.query("DELETE FROM otps WHERE id = $1",[otp.id]); throw new ApiError("OTP has expired. Please request a new one.",400); } if (otp.attempts >= 5) { await db.query("DELETE FROM otps WHERE id = $1",[otp.id]); throw new ApiError("Maximum verification attempts exceeded. Please request a new OTP.",400); } if (!(await verifySecret(otpValue,otp.otp_hash))) { const attempts = otp.attempts + 1; if (attempts >= 5) await db.query("DELETE FROM otps WHERE id = $1",[otp.id]); else await db.query("UPDATE otps SET attempts = $1 WHERE id = $2",[attempts,otp.id]); throw new ApiError(attempts >= 5 ? "Maximum verification attempts exceeded. Please request a new OTP." : `Invalid OTP. ${5-attempts} attempts remaining.`,400); } await db.query("UPDATE users SET is_verified = true, updated_at = $1 WHERE id = $2",[now(),user.id]); await db.query("DELETE FROM otps WHERE id = $1",[otp.id]); } const tokens=await tokenPair(user.id,env); await db.query("INSERT INTO sessions (id,user_id,refresh_token_hash,is_revoked,created_at,expires_at) VALUES ($1,$2,$3,false,$4,$5)",[uuid(),user.id,await hashSecret(tokens.refresh_token),now(),addDays(Number(env.REFRESH_TOKEN_EXPIRE_DAYS||30))]); return json(tokens,200,request); }
  if (path === "/api/v1/auth/resend-otp" && method === "POST") { const data=await body(request); const { rows:[user] }=await db.query("SELECT * FROM users WHERE email=$1",[requireString(data.email,"email").toLowerCase()]); if(!user) throw new ApiError("User not found.",404); if(user.is_verified) throw new ApiError("User email is already verified.",400); await issueOtp(env,db,user); return json({message:"OTP sent successfully."},200,request); }
  if (path === "/api/v1/auth/login" && method === "POST") { const data=await body(request); const identifier=requireString(data.email_or_username,"email_or_username"); const { rows:[user] }=await db.query("SELECT * FROM users WHERE email=$1 OR username=$2",[identifier,identifier]); if(!user || !(await verifySecret(requireString(data.password,"password"),user.hashed_password))) throw new ApiError("Invalid credentials.",401); if(!user.is_verified) throw new ApiError("Email is not verified. Please verify your OTP first.",403); if(!user.is_active) throw new ApiError("Account is disabled.",403); const tokens=await tokenPair(user.id,env); await db.query("UPDATE users SET last_login=$1, updated_at=$1 WHERE id=$2",[now(),user.id]); await db.query("INSERT INTO sessions (id,user_id,refresh_token_hash,is_revoked,created_at,expires_at) VALUES ($1,$2,$3,false,$4,$5)",[uuid(),user.id,await hashSecret(tokens.refresh_token),now(),addDays(Number(env.REFRESH_TOKEN_EXPIRE_DAYS||30))]); return json(tokens,200,request); }
  if (path === "/api/v1/auth/refresh" && method === "POST") { const data=await body(request); const refresh=requireString(data.refresh_token,"refresh_token"); let payload; try { payload=await readJwt(refresh,env.JWT_SECRET_KEY); } catch { throw new ApiError("Invalid or expired refresh token.",401); } if(payload.type!=="refresh"||!payload.sub) throw new ApiError("Invalid token type.",401); const { rows:[user] }=await db.query("SELECT * FROM users WHERE id=$1 AND is_active=true",[payload.sub]); const { rows:sessions }=await db.query("SELECT * FROM sessions WHERE user_id=$1 AND is_revoked=false AND expires_at>$2",[payload.sub,now()]); if(!user || !(await Promise.all(sessions.map((session)=>verifySecret(refresh,session.refresh_token_hash)))).some(Boolean)) throw new ApiError("Session revoked or invalid.",401); const tokens=await tokenPair(user.id,env); return json({...tokens,refresh_token:refresh},200,request); }
  if (path === "/api/v1/auth/logout" && method === "POST") { const user=await currentUser(request,env,db); const data=await body(request); const sessions=(await db.query("SELECT * FROM sessions WHERE user_id=$1 AND is_revoked=false",[user.id])).rows; const matches=await Promise.all(sessions.map((session)=>verifySecret(requireString(data.refresh_token,"refresh_token"),session.refresh_token_hash))); const ids=sessions.filter((_,index)=>matches[index]).map((session)=>session.id); if(!ids.length) throw new ApiError("Active session not found or already logged out.",400); await db.query("UPDATE sessions SET is_revoked=true WHERE id = ANY($1::varchar[])",[ids]); return json({message:"Successfully logged out."},200,request); }
  if (path === "/api/v1/auth/me" && method === "GET") return json(userResponse(await currentUser(request,env,db)),200,request);
  if (path === "/api/v1/profile/username" && method === "PATCH") { const user=await currentUser(request,env,db); const value=requireString((await body(request)).username,"username",3,30); if(!/^[A-Za-z0-9_]+$/.test(value)) throw new ApiError("username is invalid.",422); if(value===user.username) return json({message:"Username is already set to this value.",username:value},200,request); if((await db.query("SELECT id FROM users WHERE username=$1",[value])).rows[0]) throw new ApiError("Username is already taken.",409); await db.query("UPDATE users SET username=$1,updated_at=$2 WHERE id=$3",[value,now(),user.id]); return json({message:"Username updated successfully.",username:value},200,request); }
  if (path === "/api/v1/profile/refer-id" && method === "PATCH") { const user=await currentUser(request,env,db); const value=requireString((await body(request)).refer_id,"refer_id",4,20); if(!/^[A-Za-z0-9_]+$/.test(value)) throw new ApiError("refer_id is invalid.",422); if(value===user.refer_id) return json({message:"Referral ID is already set to this value.",refer_id:value},200,request); if((await db.query("SELECT id FROM users WHERE refer_id=$1",[value])).rows[0]) throw new ApiError("This referral ID is already taken.",409); await db.query("UPDATE users SET refer_id=$1,updated_at=$2 WHERE id=$3",[value,now(),user.id]); return json({message:"Referral ID updated successfully.",refer_id:value},200,request); }
  if (path === "/api/v1/profile/avatar" && method === "POST") { const user=await currentUser(request,env,db); const file=(await request.formData()).get("file"); if(!(file instanceof File)) throw new ApiError("file is required.",422); if(!allowedAvatarTypes.has(file.type)) throw new ApiError(`Unsupported file type '${file.type}'. Accepted: jpeg, png, webp, gif, heic.`,415); if(file.size>5*1024*1024) throw new ApiError("File too large. Maximum allowed size is 5 MB.",413); if(!env.ASSETS) throw new ConfigurationError("ASSETS binding is missing."); const base=String(env.R2_PUBLIC_URL||"").replace(/\/$/,""); if(!base||base.includes("REPLACE_WITH")) throw new ConfigurationError("R2_PUBLIC_URL is missing."); const key=`avatars/${user.id}.webp`; await env.ASSETS.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:"public, max-age=31536000, immutable"}}); const avatarUrl=`${base}/${key}`; await db.query("UPDATE users SET avatar_url=$1,updated_at=$2 WHERE id=$3",[avatarUrl,now(),user.id]); return json({message:"Avatar uploaded successfully.",avatar_url:`${avatarUrl}?v=${Date.now()}`},200,request); }
  if (path === "/api/v1/profile/avatar" && method === "DELETE") { const user=await currentUser(request,env,db); if(!user.avatar_url) throw new ApiError("No avatar to delete.",404); await env.ASSETS.delete(`avatars/${user.id}.webp`); await db.query("UPDATE users SET avatar_url=NULL,updated_at=$1 WHERE id=$2",[now(),user.id]); return json({message:"Avatar removed successfully."},200,request); }
  if (path === "/api/v1/streaks/me" && method === "GET") return json(await streakResponse(db,await currentUser(request,env,db)),200,request);
  if (path === "/api/v1/streaks/claim" && method === "POST") { const user=await currentUser(request,env,db); const existing=await streakResponse(db,user); if(existing.last_claim_date===today()) return json({message:"Streak already claimed for today.",current_streak:existing.current_streak,highest_streak:existing.highest_streak,claimed_today:true,coupon_unlocked:existing.star_coupon_tier},200,request); const yesterday=new Date(Date.now()-86_400_000).toISOString().slice(0,10); const current=existing.last_claim_date===yesterday?existing.current_streak+1:1; const highest=Math.max(existing.highest_streak,current); await db.query("UPDATE streaks SET current_streak=$1,highest_streak=$2,last_claim_date=$3 WHERE id=$4",[current,highest,today(),existing.id]); const {rows:[refs]}=await db.query("SELECT COUNT(*)::int AS count FROM referrals WHERE referrer_id=$1",[user.id]); return json({message:"Daily streak claimed successfully!",current_streak:current,highest_streak:highest,claimed_today:true,coupon_unlocked:couponTier(current,refs.count)},200,request); }
  if (path === "/api/v1/referrals/me" && method === "GET") { const user=await currentUser(request,env,db); let code=user.refer_id; if(!code){ do { code=Array.from(crypto.getRandomValues(new Uint8Array(8)),(v)=>"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"[v%36]).join(""); } while((await db.query("SELECT id FROM users WHERE refer_id=$1",[code])).rows[0]); await db.query("UPDATE users SET refer_id=$1,updated_at=$2 WHERE id=$3",[code,now(),user.id]); } const {rows}=await db.query("SELECT u.id,u.username,u.created_at FROM referrals r JOIN users u ON u.id=r.referred_user_id WHERE r.referrer_id=$1",[user.id]); return json({referral_code:code,total_referrals:rows.length,referred_users:rows},200,request); }
  if (path === "/api/v1/referrals/claim" && method === "POST") { const user=await currentUser(request,env,db); const code=requireString((await body(request)).referral_code,"referral_code"); const {rows:[referrer]}=await db.query("SELECT * FROM users WHERE refer_id=$1 OR username=$1",[code]); if(!referrer) throw new ApiError("Referral code or user not found.",404); if(referrer.id===user.id) throw new ApiError("You cannot use your own referral code.",400); if((await db.query("SELECT id FROM referrals WHERE referred_user_id=$1",[user.id])).rows[0]) throw new ApiError("You have already claimed a referral code.",400); const referral={id:uuid(),referrer_id:referrer.id,referred_user_id:user.id,created_at:now()}; await db.query("INSERT INTO referrals (id,referrer_id,referred_user_id,created_at) VALUES ($1,$2,$3,$4)",[referral.id,referral.referrer_id,referral.referred_user_id,referral.created_at]); return json(referral,201,request); }
  if (path === "/api/v1/games" && method === "POST") { await currentUser(request,env,db); const data=await body(request); const title=requireString(data.title,"title",1,100); const url=requireString(data.url,"url"); try{new URL(url);}catch{throw new ApiError("url is invalid.",422);} if((await db.query("SELECT id FROM games WHERE url=$1",[url])).rows[0]) throw new ApiError("Game URL already registered.",400); const {rows:[game]}=await db.query("INSERT INTO games (id,title,url,is_active,created_at,thumbnail_url,is_latest,likes_count,plays_count,added_at) VALUES ($1,$2,$3,true,$4,$5,$6,0,0,$4) RETURNING *",[uuid(),title,url,now(),typeof data.thumbnail_url==="string"?data.thumbnail_url:null,Boolean(data.is_latest)]); return json({...game,is_liked:false},201,request); }
  if (path === "/api/v1/games" && method === "GET") { const {rows}=await db.query("SELECT id,title,url,thumbnail_url,is_latest,likes_count,plays_count,added_at FROM games WHERE is_active=true"); return json(rows.map((game)=>({...game,is_liked:false})),200,request); }
  const gameMatch=path.match(/^\/api\/v1\/games\/([^/]+)(?:\/(like|play))?$/); if(gameMatch){const [,id,action]=gameMatch; const {rows:[game]}=await db.query("SELECT * FROM games WHERE id=$1 AND is_active=true",[id]); if(!game)throw new ApiError("Game not found.",404); if(!action&&method==="GET")return json({...game,is_liked:false},200,request); if(action==="like"&&method==="POST"){await currentUser(request,env,db);await db.query("UPDATE games SET likes_count=likes_count+1 WHERE id=$1",[id]);return json({message:"Liked game.",active:true},200,request);} if(action==="play"&&method==="POST"){await db.query("UPDATE games SET plays_count=plays_count+1 WHERE id=$1",[id]);return json({message:"Gameplay recorded.",active:true},200,request);}}
  if(path==="/api/v1/analytics/me"&&method==="GET"){const user=await currentUser(request,env,db);let {rows:[usage]}=await db.query("SELECT * FROM daily_usage WHERE user_id=$1 AND usage_date=$2",[user.id,today()]);if(!usage){const id=uuid();({rows:[usage]}=await db.query("INSERT INTO daily_usage (id,user_id,usage_date,banner_ads,interstitial_ads,rewarded_ads,native_ads) VALUES ($1,$2,$3,0,0,0,0) RETURNING *",[id,user.id,today()]));}return json(usage,200,request);}
  if(path==="/api/v1/analytics/ads"&&method==="POST"){const user=await currentUser(request,env,db);const data=await body(request);const column={banner:"banner_ads",interstitial:"interstitial_ads",rewarded:"rewarded_ads",native:"native_ads"}[requireString(data.ad_type,"ad_type").toLowerCase()];const count=data.count===undefined?1:Number(data.count);if(!column||!Number.isInteger(count)||count<1)throw new ApiError("Invalid ad_type or count.",400);let {rows:[usage]}=await db.query("SELECT * FROM daily_usage WHERE user_id=$1 AND usage_date=$2",[user.id,today()]);if(!usage){await db.query("INSERT INTO daily_usage (id,user_id,usage_date,banner_ads,interstitial_ads,rewarded_ads,native_ads) VALUES ($1,$2,$3,0,0,0,0)",[uuid(),user.id,today()]);}({rows:[usage]}=await db.query(`UPDATE daily_usage SET ${column}=${column}+$1 WHERE user_id=$2 AND usage_date=$3 RETURNING *`,[count,user.id,today()]));return json(usage,200,request);}
  throw new ApiError("Not found.",404);
}

export default { async fetch(request, env) { if(request.method==="OPTIONS") return new Response(null,{status:204,headers:cors(request)}); try { return await withDb(env,(db)=>handleApi(request,env,db)); } catch(error) { if(error instanceof ApiError) return json({detail:error.message},error.status,request); if(error instanceof ConfigurationError) { console.error(error.message); return json({detail:"The Worker is not configured."},503,request); } console.error(error); return json({detail:"Internal server error."},500,request); } } };
