"""Add OTP attempts

Revision ID: 109d2761c9c6
Revises: 95e709d0d272
Create Date: 2026-07-27 00:02:46.776224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109d2761c9c6'
down_revision: Union[str, Sequence[str], None] = '95e709d0d272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('is_used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'is_used')
    # ### end Alembic commands ###
