"""Add city and country to traffic_logs

Revision ID: 1cb97329c95e
Revises: d9f8012fd00d
Create Date: 2026-07-27 01:27:22.489654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb97329c95e'
down_revision: Union[str, Sequence[str], None] = 'd9f8012fd00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_logs', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('traffic_logs', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic_logs', 'country')
    op.drop_column('traffic_logs', 'city')
    # ### end Alembic commands ###
