"""Add OTP attempts

Revision ID: 95e709d0d272
Revises: 2a2cb1cc3048
Create Date: 2026-07-27 00:00:04.418222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e709d0d272'
down_revision: Union[str, Sequence[str], None] = '2a2cb1cc3048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'attempts')
    # ### end Alembic commands ###
