"""update schema1

Revision ID: c0148255fe0f
Revises: 93a40e876d54
Create Date: 2026-08-14 01:11:54.276067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0148255fe0f'
down_revision: Union[str, Sequence[str], None] = '93a40e876d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemptions', sa.Column('upi_id', sa.String(length=100), nullable=False))
    op.add_column('redemptions', sa.Column('full_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redemptions', 'full_name')
    op.drop_column('redemptions', 'upi_id')
    # ### end Alembic commands ###
